version: 2
jobs:
  build:
    working_directory: /home/mo/circulate
    docker:
      - image: python:3.6.0
        environment:
          FLASK_APP: autoapp.py
          FLASK_DEBUG: 1
    steps:
      - checkout
      - run:
          name: install deps
          command: pip install -r requirements/dev.txt

      - run:
          name: run tests
          command: flask test
  deploy-job:
    docker:
      - image: ruby:2.5.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: cd $CIRCLE_WORKING_DIRECTORY/deploy/capistrano/; bundle check || bundle install
      - run:
          name: Deploy if tests pass and branch is Master
          command: cd $CIRCLE_WORKING_DIRECTORY/deploy/capistrano/; bundle exec cap production deploy
