version: 2
jobs:
  test:
    working_directory: /home/mo/circulate
    docker:
      - image: python:3.6.0
        environment:
          FLASK_APP: autoapp.py
          FLASK_DEBUG: 1
    steps:
      - checkout
      - run:
          name: install deps
          command: pip install -r requirements/dev.txt

      - run:
          name: run tests
          command: flask test
  deploy:
    working_directory: /home/mo/circulate
    docker:
      - image: ruby:2.5.8
        environment:
          FLASK_APP: autoapp.py
          FLASK_DEBUG: 1
    steps:
      - checkout
      - run:
          name: install bundler
          command: cd deploy/capistrano; gem install bundler
      - run:
          name: Bundle Install
          command: cd deploy/capistrano; bundle install
      - run:
          name: Deploy production
          command: cd deploy/capistrano; bundle exec cap production deploy

workflows:
    version: 2
    test_and_deploy:
      jobs:
        - test
        - deploy
# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - deploy-job:
#         - requires:
#           - flask-test

# jobs:
  # flask-test:
  #   working_directory: /home/mo/circulate
  #   docker:
  #     - image: python:3.6.0
  #       environment:
  #         FLASK_APP: autoapp.py
  #         FLASK_DEBUG: 1
  #   steps:
  #     - checkout
  #     - run:
  #         name: install deps
  #         command: pip install -r requirements/dev.txt

  #     - run:
  #         name: run tests
  #         command: flask test
#   #  build and test jobs go here - not included for brevity
