# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Load the SCM plugin appropriate to your project:
#
# require "capistrano/scm/hg"
# install_plugin Capistrano::SCM::Hg
# or
# require "capistrano/scm/svn"
# install_plugin Capistrano::SCM::Svn
# or
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Include tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#   https://github.com/capistrano/passenger
#
# require "capistrano/rvm"
# require "capistrano/rbenv"
# require "capistrano/chruby"
# require "capistrano/bundler"
# require "capistrano/rails/assets"
# require "capistrano/rails/migrations"
# require "capistrano/passenger"

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }

namespace :deploy do
  task :flask_build do
    on roles(:all) do
      execute "cd '#{release_path}'; pip3 install -r requirements/prod.txt"
    end
  end

  task :migration do
    on roles(:db) do
      puts "put FLASK_APP env"
      execute "echo $FLASK_APP"
      puts "after set"
      execute "export FLASK_APP=#{release_path}/autoapp.py"
      execute "echo $FLASK_APP"
      execute "cd '#{release_path}'; python3 -m flask db migrate"
    end
  end

  desc "flask gunicorn server"
  task :restart do
    on roles(:web) do
      puts "stop flask gunicorn server"
      execute "kill -9 $(ps aux | grep gunicorn | awk '{print $2}')"
      execute "sleep 1"
      puts "start flask gunicorn server"
      execute "cd '#{release_path}';/home/ubuntu/.local/bin/gunicorn autoapp:app -b 0.0.0.0:5000 --reload --daemon"
    end
  end

  before :finishing, :flask_build
  before :finishing, :migration
  after :finishing, :restart
end
